### ISSUE TITLE
text

### ISSUE THREAD

**Issue by hofmannv** [Materials-Data-Science-and-Informatics/survey_dashboard#16]
Work over intro texts and structure them visually.

current text: 

> Explorer interactively the HMC 2021 Survey results. The overview sections displays some main results, while you can apply some global filters to these. Find out what methods, tools, software and standards are applied by others in your research area. The question explorer allows for in detail analyzis of a specific question and simple correlations of two questions. Interact with the visualizations and widgets on the left to explorer the data. The corresponding Data publication of the survey is available [here](https://doi.org/10.7802/2433).

> DISCLAIMER: Be careful in drawing any conclusions, especially on filtered results! The usable sample size of the survey 2021 was 2.3% of all Helmholtz employees at the time, of which only the onces are published and displayed who provided consent. Therefore, the sample is often to small to be an accurate representation of the whole HGF and or to unbiased accurately sample the underlying true distributions!

> Any Feedback is welcome and can be given [here](https://github.com/Materials-Data-Science-and-Informatics/survey_dashboard)

**Comment by hofmannv** [comment]
### Global data filters
Select some data filters to apply. You can filter global by research area and or by data generation method.

### Overview
Birds eye view of survey results related to research data management.

### Methods, Tools and software
Find out about the tools and methods used in the research area and data generation method you filtered for.

### Survey data explorer

**Comment by SilkeGerlich** [comment]
Also: add link / reference to Survey report:
https://doi.org/10.3289/HMC_publ_05

**Comment by hofmannv** [comment]
> Also: add link / reference to Survey report: https://doi.org/10.3289/HMC_publ_05

if not done in #13

**Comment by broeder-j** [comment]
Comment to this: all text beyond the plots can be seen here: 

https://github.com/Materials-Data-Science-and-Informatics/survey_dashboard/blob/hmc_specific/survey_dashboard/text_display.py

And for the questions here:

https://github.com/Materials-Data-Science-and-Informatics/survey_dashboard/blob/hmc_specific/survey_dashboard/data/display_specifications/hcs_clean_dictionaries.py

**Comment by hofmannv** [comment]
Who are the data stakeholders in Helmholtz? What tools do they use? What are the roadblocks to better metadata? 
These were some of the questions that we investigated with our HMC community survey in 2021. Here you can browse the results interactively and get your own picture!

[ICONS]

The HMC Survey Data Explorer consists of 4 parts:
    • Global data filters – refine the displayed data in all panels.
    • Data stakeholders – get an insight of community profiles
    • Data generation and handling – check methods, tools and software used
    • Survey data explorer – explore and compare responses to different survey questions

DISCLAIMER: Display data should be interpreted with care. Responses might be subject to sample bias and some questions were specific to the research field of participants. Check our written publication for further details

Global data filters
Apply filters to displayed data according to research areas and data generation method
Research area
Data generation method

Data stakeholders
[del]

Data generation and handling
Discover the scientific methods, used software and repositories of our communities

Survey data explorer
Select two questions to explore answers and see how they correspond to one another
Question 1
Question 2
Correspondence of selected questions



* Displayed data is based on the cleaned and fully anonymized published data set[link]

**Comment by hofmannv** [comment]
@SilkeGerlich will deepl to GER and silkefy.

**Comment by SilkeGerlich** [comment]
### HERE IS MY REVISED VERSION

Who are the data stakeholders in Helmholtz? What tools do they use? What are the roadblocks to better metadata?
These were some of the questions that we investigated with our HMC community survey in 2021. Here you can browse the results interactively and _dive deeper into the data!_

`icons`
1. _**49** survey questions_
2. _**631** researchers took part in the survey_
3. _Find the [**complete dataset** online](https://search.gesis.org/research_data/SDN-10.7802-2433){target="_blank} _

`/icons`

_Refine the displayed data with **global Data Filters**
and explore

- the community profiles of our **Data Stakeholders**
- the methods, tools and software used for **Data Generation and Handling**.
- individual and coresponding answers to different questions in the **Survey Data Explorer**_

`in a box`
DISCLAIMER: Displayed data should be interpreted with care. Responses might be subject to sample bias and some questions were specific to the research field of participants. Check our [written publication](https://doi.org/10.3289/HMC_publ_05) for further details
`/in a box`

Got feedback? [Contact us on Github](https://github.com/Materials-Data-Science-and-Informatics/survey_dashboard/issues){target="_blank}

Global data filters
Apply filters to displayed data according to research areas and data generation method
Research area
Data generation method

Data stakeholders
[del]

Data generation and handling
Discover the scientific methods, used software and repositories of our communities

Survey data explorer
Select two questions to explore answers and see how they correspond to one another
Question 1
Question 2
Correspondence of selected questions

 Displayed data is based on the cleaned and fully anonymized [published data set](https://doi.org/10.3289/HMC_publ_05){target="_blank}

**Comment by SilkeGerlich** [comment]
@broeder-j  Still not sure, whether it is more sensible  to add the text to the panel or include it in the HTML. At least the first few paragraphs, that are not directly linked to the interactive elements. What do you think?

**Comment by broeder-j** [comment]
Actuallly this I think is a good idea. And while we are at it (since I know now how the jinjia template works) one could also think of Moving the accordion and embbed  all the Plots and widgets. This would be a way to allowed for a fancy accordion or whatever and have all descriptive Text in hmc style. Getting the font into panel is not so easy.

**Comment by hofmannv** [comment]
i like the revised verison of the text!

some minor things: 
- instead of `individual and coresponding answers to different questions in the Survey Data Explorer` i would propse to go with something like `responses and how they compare to each other between different quesitons in the Survey Data Explorer`
- not `Responses` are not potentially subject to sample bias, but the `data set`
- are we really only interested in positive Feedback? Maybe also in questions?

**Comment by SilkeGerlich** [comment]
>     * are we really only interested in positive Feedback? Maybe also in questions?

I don't understand "feedback" as positive only :thinking: 
Including questions is fine, I think.

**Comment by SilkeGerlich** [comment]
Done

**Comment by broeder-j** [comment]
I still have to update the text in the app itself.
