### ISSUE TITLE
Visual adjustments of FrontEnd

### ISSUE THREAD

**Issue by hofmannv** [Materials-Data-Science-and-Informatics/survey_dashboard#23]
From the HMC Front-Office we are asked to: 
- add a linked-in Icon to https://www.linkedin.com/company/helmholtz-metadata-collaboration-hmc
- adjust the link to the "impressum & datenschutz" in a way that it opens in a new window

Contact point in the office is Lena.

**Comment by broeder-j** [comment]
I can do this. 
But both things requested are not like this on the HMC webpage:

There is now linked in Icon and also the 'datenschutz' does not open in a new window.
Are they going to change this?

**Comment by hofmannv** [comment]
checking with the webpage adim/content developer at the HMC office

**Comment by hofmannv** [comment]
Ok. Here is what I propose: 

1. regarding LinkedIn Logo we wait until its added to the main page, in order to do it the exact same way (otherwise we have to do it twice). 

2. regarding protechtion and imprint: These link to the FZJ data policy and the FZJ legal notice. Your suggestion @lenaheel is that these should open in **New Browser windows** because they appear in a different layout - correct?

if 2 is a yes, then it should be easy to implement and can be done right away.

**Comment by lenaheel** [comment]
Yes, it should open in a new browser window/tab

_(It actually has nothing to do with the fact that the layout changes when you are redirected to the FZJ website. Instead, it is just more comfortable/easier for the user to stay on the dashboard page when the link opens in a new tab)_

**Comment by lenaheel** [comment]
LinkedIn Social Icon is on the HMC website now

**Comment by broeder-j** [comment]
done it commit ce8ede06.
will be deployed soon
