### ISSUE TITLE
General visual adjustment

### ISSUE THREAD

**Issue by hofmannv** [Materials-Data-Science-and-Informatics/survey_dashboard#9]
- [x] remove inactive menu from HMC webpage 
- [x] add aheader picture 
- [x] add a survey-dashboard logo
- [x] adjust fonts, colors according tho HMC CI

**Comment by SilkeGerlich** [comment]
@hofmannv 

Where can I find the header picture and the logo?

**Comment by hofmannv** [comment]
- we can either use the one from hub matters dashboard or create an own one. 
- a logo does not yet exist

**Comment by hofmannv** [comment]
banner: https://fairdashboard.helmholtz-metadaten.de/assets/Banner.png

**Comment by SilkeGerlich** [comment]
Done
